### ISSUE TITLE
Would the BGC distance be output in the files?

### ISSUE THREAD

**Issue by ChenTianYi99** [nselem/bigscape-corason#10]
Hello,

You said that BGC distance was calculated by the weighted combination of the Jaccard Index (JI), adjacency index (AI), and domain sequence similarity (DSS). I indeed find these indices in the network files, but i am not sure whether i could find the BGC distance value directly in the file or i need to calculate the distance manually.

Looking forward to your reply. Thanks in advance.

**Comment by jorgecnavarrom** [comment]
Hi,

The combined metrics value is in the third column of the .network file (column "Raw distance")

**Comment by ChenTianYi99** [comment]
Thanks.
Hope you well.
