### ISSUE TITLE
Use of Cytoscape

### ISSUE THREAD

**Issue by ReynaldoVien** [nselem/bigscape-corason#11]
I downloaded the similarity network files from BigScape, however I don't know which file I should upload to Cytoscape and under what parameters to be able to visualize my similarity networks and edit them to obtain the final image.
Hope you can help me.

**Comment by jorgecnavarrom** [comment]
Hi
Basically: you use the .network files which contain the distances calculated by BiG-SCAPE:
![20221115_104453 cytoscape importing](https://user-images.githubusercontent.com/17873739/201887389-f53207e4-c2e2-4846-ad23-76cbd7edd1c5.png)

The clustering (tsv) files can be imported (File -> Import -> Table from file) also as properties

**Comment by ReynaldoVien** [comment]
Thanks! it worked
